<?php

return [
    [
        'name'        => 'label_bank_name',
        'label'       => 'Label bank name',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Label bank name',
    ],
    [
        'name'        => 'bank_name',
        'label'       => 'Bank name',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Your bank name',
    ],
    [
        'name'        => 'label_account_holder_name',
        'label'       => 'Label account holder name',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Label account holder name',
    ],
    [
        'name'        => 'account_holder_name',
        'label'       => 'Account holder name',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Bank account holder name',
    ],
    [
        'name'        => 'label_account_number',
        'label'       => 'Label account number',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Label bank account number',
    ],
    [
        'name'        => 'account_number',
        'label'       => 'Account number',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Your bank account number',
    ],
    [
        'name'        => 'label_amount',
        'label'       => 'Label amount',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Label amount',
    ],
    [
        'name'        => 'label_number',
        'label'       => 'Label number',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Label number',
    ],
    [
        'name'        => 'step_1',
        'label'       => 'Step 1',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Step 1',
    ],
    [
        'name'        => 'step_2',
        'label'       => 'Step 2',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Step 2',
    ],
    [
        'name'        => 'step_3',
        'label'       => 'Step 3',
        'type'        => 'string',
        'required'    => true,
        'rules'       => 'required',
        'description' => 'Step 3',
    ],
];
